# Generated by Django 4.2 on 2023-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0037_alter_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmsg',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
